# Generated by Django 5.1.2 on 2024-11-15 20:56

import crud_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_usuario_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('ubicacion', models.CharField(choices=[('Montería', 'Montería'), ('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio_renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to=crud_app.models.upload_to)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='crud_app.usuario')),
            ],
        ),
    ]
