# Generated by Django 5.1.2 on 2024-11-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_invitados', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en horas')),
                ('correo_usuario', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='crud_app.eventos')),
                ('usuario_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_realizadas', to='crud_app.usuario')),
            ],
        ),
    ]
