# Generated by Django 5.1.2 on 2024-11-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_remove_reserva_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='correo_usuario',
        ),
    ]
